ACTION_CLICK_RETURN = "Click & Return"
ACTION_CLICK_STAY = "Click & Stay"
ACTION_DOUBLE_CLICK_RETURN = "Double Click & Return"
ACTION_DRAG_RETURN = "Drag & Return"
ACTION_MACRO = "Macro / Sequence"
ACTION_TEXT = "Text / Type"

ACTION_TYPES = [
    ACTION_CLICK_RETURN,
    ACTION_CLICK_STAY,
    ACTION_DOUBLE_CLICK_RETURN,
    ACTION_DRAG_RETURN,
    ACTION_MACRO
]

DEFAULT_FONT = 'Segoe UI'
PROFILES_FILE = 'profiles.json'
ICON_FILE = 'icon.ico'

